// This file is auto-generated by python-be/scripts/generate_sfx_catalog.py.
export const SFX_CATALOG = [
  'cartoon/boing.mp3',
  'cartoon/cartoon-slip.mp3',
  'cartoon/throw.mp3',
  'emotion/applause.mp3',
  'emotion/disapointed.mp3',
  'emotion/shock.mp3',
  'emphasis/ding.mp3',
  'tech/camera-click.mp3',
  'tech/notification.mp3',
  'ui/bubble-pop.mp3',
  'ui/keyboard-typing.mp3',
  'ui/mouse-click.mp3',
  'ui/notification.mp3',
  'ui/pop.mp3',
  'ui/swipe.mp3',
  'whoosh/whoosh.mp3',
] as const;
